NDefines.NMilitary.LAND_COMBAT_COLLATERAL_FACTOR = 0.025
NDefines.NMilitary.DISBAND_MANPOWER_LOSS = 0.70
NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.25
NDefines.NGame.START_DATE = "1917.1.1.1"
NDefines.NGame.EVENT_TIMEOUT_DEFAULT = 3
NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048 
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512 
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10 
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196 
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41 
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000 
NDefines.NCountry.STATE_OCCUPATION_COST_MULTIPLIER = 0.05 
NDefines.NDiplomacy.MAX_OPINION_VALUE = 200 
NDefines.NDiplomacy.MIN_OPINION_VALUE = -200 
NDefines.NDiplomacy.VERY_GOOD_OPINION = 100 
NDefines.NDiplomacy.VERY_BAD_OPINION = -100 
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0 
NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = -0.1 
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.1 
NDefines.NCountry.WAR_SUPPORT_TENSION_IMPACT = 0.15

NDefines.NAI.FASCISTS_BEFRIEND_FASCISTS = 10 
NDefines.NAI.FASCISTS_BEFRIEND_DEMOCRACIES = -25 
NDefines.NAI.FASCISTS_BEFRIEND_COMMUNISTS = -75 
NDefines.NAI.FASCISTS_ALLY_FASCISTS = 0 
NDefines.NAI.FASCISTS_ALLY_DEMOCRACIES = -50 
NDefines.NAI.FASCISTS_ALLY_COMMUNISTS = -100 
NDefines.NAI.FASCISTS_ANTAGONIZE_FASCISTS = -10 
NDefines.NAI.FASCISTS_ANTAGONIZE_DEMOCRACIES = 50 
NDefines.NAI.FASCISTS_ANTAGONIZE_COMMUNISTS = 100 
NDefines.NAI.DEMOCRACIES_BEFRIEND_FASCISTS = -25 
NDefines.NAI.DEMOCRACIES_BEFRIEND_DEMOCRACIES = 0 
NDefines.NAI.DEMOCRACIES_BEFRIEND_COMMUNISTS = -25 
NDefines.NAI.DEMOCRACIES_ALLY_FASCISTS = -50 
NDefines.NAI.DEMOCRACIES_ALLY_DEMOCRACIES = 0 
NDefines.NAI.DEMOCRACIES_ALLY_COMMUNISTS = -50 
NDefines.NAI.DEMOCRACIES_ANTAGONIZE_FASCISTS = 0 
NDefines.NAI.DEMOCRACIES_ANTAGONIZE_DEMOCRACIES = -25 
NDefines.NAI.DEMOCRACIES_ANTAGONIZE_COMMUNISTS = 0 
NDefines.NAI.COMMUNISTS_BEFRIEND_FASCISTS = -25 
NDefines.NAI.COMMUNISTS_BEFRIEND_DEMOCRACIES = -25 
NDefines.NAI.COMMUNISTS_BEFRIEND_COMMUNISTS = 25 
NDefines.NAI.COMMUNISTS_ALLY_FASCISTS = -100 
NDefines.NAI.COMMUNISTS_ALLY_DEMOCRACIES = -50 
NDefines.NAI.COMMUNISTS_ALLY_COMMUNISTS = 0 
NDefines.NAI.COMMUNISTS_ANTAGONIZE_FASCISTS = 100 
NDefines.NAI.COMMUNISTS_ANTAGONIZE_DEMOCRACIES = 10
NDefines.NAI.COMMUNISTS_ANTAGONIZE_COMMUNISTS = -10

NDefines.NDiplomacy.NOT_READY_FOR_WAR_BASE = -100
NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = -0.1 

NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 10
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_GAIN = 2 

NDefines.NBuildings.BASE_FACTORY_REPAIR = 0.2
NDefines.NBuildings.BASE_FACTORY_REPAIR_FACTOR = 1.5

NDefines.NAI.MAX_SUPPLY_DIVISOR = 2.5

NDefines.NAI.DEMOCRATIC_AI_FACTION_KICKING_PLAYER_THREAT_DIFFERENCE = 35

NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.03
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.058
NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.003

NDefines.NMilitary.ENCIRCLED_PENALTY = -0.44
NDefines.NMilitary.COMBAT_SUPPLY_LACK_IMPACT = -0.44

NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "1917.1.1.1"

NDefines_Graphics.NGraphics.POLITICAL_GRID_SMALL_BOX_LIMIT = 12